name: app_environment
channels:
  - snowflake
dependencies:
  - plotly=5.24.1
  - prophet=1.1.5
  - python=
  - python-kaleido=0.2.1
  - scikit-learn=1.6.1
  - snowflake-snowpark-python=
  - statsmodels=0.14.4
  - streamlit=1.45.0
